name: 02_DEVExport
# Export solution from DEV environment
#  unpack it and prepare, commit and push

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      DEVSECRET:
        description: 'A token passed from the caller workflow'
        required: false

env:
  DEV_ENVIRONMENT_URL: 'https://org859aecd5.crm16.dynamics.com/'
  DEV_CLIENT_ID: '20e6d751-0038-4647-ab6e-2ecc5286aec7'
  DEV_TENANT_ID: '189fc259-0274-4dfb-b187-e2b6dcaf0e88'
  SOLUTION_NAME: PocketInvest
permissions:
  contents: write
jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: ${{env.DEV_ENVIRONMENT_URL}}
        app-id: ${{env.DEV_CLIENT_ID}}
        client-secret: ${{ inputs.DEVSECRET }}
        tenant-id: ${{env.DEV_TENANT_ID}}

    - name: Install PAC
      if: github.event_name == 'release'
      uses: microsoft/powerplatform-actions/actions-install@v1.1.0
    
    - name: Power Platform Set Online Solution Version
      if: github.event_name == 'release'
      uses: microsoft/powerplatform-actions/set-online-solution-version@v1.1.0
      with:
        environment-url: ${{env.DEV_ENVIRONMENT_URL}}
        app-id: ${{env.DEV_CLIENT_ID}}
        client-secret: ${{ inputs.DEVSECRET }}
        tenant-id: ${{env.DEV_TENANT_ID}}
        name: PocketInvest
        version: ${{github.event.release.tag_name}}
        
    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{env.DEV_ENVIRONMENT_URL}}
        app-id: ${{env.DEV_CLIENT_ID}}
        client-secret: ${{ inputs.DEVSECRET }}
        tenant-id: ${{env.DEV_TENANT_ID}}
        solution-name: ${{ env.SOLUTION_NAME }}
        solution-output-file: out/exported/${{ env.SOLUTION_NAME }}.zip

    - name: check-solution action
      uses: microsoft/powerplatform-actions/check-solution@v0
      with:
        environment-url: ${{env.DEV_ENVIRONMENT_URL}}
        app-id: ${{env.DEV_CLIENT_ID}}
        client-secret: ${{ inputs.DEVSECRET }}
        tenant-id: ${{env.DEV_TENANT_ID}}
        path: out/exported/${{ env.SOLUTION_NAME }}.zip

    - name: unpack-solution action
      if: ${{ success() }}
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: out/exported/${{ env.SOLUTION_NAME }}.zip
        solution-folder: ${{ env.SOLUTION_NAME }}
        solution-type: 'Unmanaged'
        overwrite-files: true
        
    - name: Commit changes
      if: ${{ success() }}
      run: |
        Remove-Item -Path "out/exported/${{ env.SOLUTION_NAME }}.zip" -Recurse -Force
        git config --global user.email "no-reply@github.com"
        git config --global user.name "GitHub Actions"
        git checkout main
        git add --all 
        git commit -m "Updates from the dev environment"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push origin main

