name: 03_BUILDArtifact_PRODImport
on:
  workflow_call:
    inputs: 
      SOLUTION_NAME:
        description: 'The solution name.'
        type: string
        default: PocketInvest       
      BUILD_ENVIRONMENT_URL:
        description: 'Build environment url.'
        type: string
        required: true      
      PRODUCTION_ENVIRONMENT_URL: 
        description: 'Production environment url.'
        type: string
        required: true
      BUILD_CLIENT_ID: 
        description: 'The BUILD client id'
        type: string
        required: true
      BUILD_TENANT_ID: 
        description: 'The BUILD tenant id'
        type: string
        required: true
      PROD_CLIENT_ID: 
        description: 'The PROD client id'
        type: string
        required: true
      PROD_TENANT_ID: 
        description: 'The PROD tenant id'
        type: string
        required: true
    secrets:
      BUILDSECRET:
        description: 'The BUILD Secret'
        required: true
      PRODSECRET:
        description: 'The PROD Secret'
        required: true

jobs:
  convert-to-managed:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Install PAC
      if: github.event_name == 'release'
      uses: microsoft/powerplatform-actions/actions-install@v1.1.0

    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@v1.4.0
      with:
        solution-folder: ${{ inputs.SOLUTION_NAME }}
        solution-file: out/solutions/${{ inputs.SOLUTION_NAME }}.zip
        solution-type: Unmanaged

    - name: Import solution as unmanaged to build env
      uses: microsoft/powerplatform-actions/import-solution@v1.4.0
      with:
        environment-url: ${{inputs.BUILD_ENVIRONMENT_URL}}
        app-id: ${{inputs.BUILD_CLIENT_ID}}
        client-secret: ${{ secrets.BUILDSECRET }}
        tenant-id: ${{inputs.BUILD_TENANT_ID}}
        solution-file: out/solutions/${{ inputs.SOLUTION_NAME }}.zip
        force-overwrite: true
        publish-changes: true

    - name: Export solution as managed
      uses: microsoft/powerplatform-actions/export-solution@v1.4.0
      with:
        environment-url: ${{inputs.BUILD_ENVIRONMENT_URL}}
        #app-id: ${{inputs.BUILD_CLIENT_ID}}
        #client-secret: ${{ secrets.BUILDSECRET }} 
        #tenant-id: ${{inputs.BUILD_TENANT_ID}}
        solution-name: ${{ inputs.SOLUTION_NAME }}
        managed: true
        solution-output-file: out/ship/${{ inputs.SOLUTION_NAME }}_managed.zip

    - name: Upload the ready to ship solution to GH artifact store
      uses: actions/upload-artifact@v2
      with:
        name: managedSolutions
        path: out/ship/

  release-to-staging:
    needs: [ convert-to-managed ]
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Fetch the ready to ship solution from GH artifact store
      uses: actions/download-artifact@v2
      with:
        name: managedSolutions
        path: out/release
    - name: Import solution to prod env
      uses: microsoft/powerplatform-actions/import-solution@v1.4.0
      with:
        environment-url: ${{inputs.PRODUCTION_ENVIRONMENT_URL}}
        app-id: ${{inputs.PROD_CLIENT_ID}}
        client-secret: ${{ secrets.PRODSECRET }}
        tenant-id: ${{inputs.PROD_TENANT_ID}}
        solution-file: out/release${{ inputs.SOLUTION_NAME }}_managed.zip
        force-overwrite: true
        publish-changes: true
