name: Export solution from DEV environment
# Export solution from DEV environment
#  unpack it and prepare, commit and push

on:
  workflow_dispatch:
  schedule:
    - cron: '00 21 * * *'

env:
  ENVIRONMENT_URL: 'https://org859aecd5.crm16.dynamics.com/'
  CLIENT_ID: '20e6d751-0038-4647-ab6e-2ecc5286aec7'
  TENANT_ID: '189fc259-0274-4dfb-b187-e2b6dcaf0e88'
  SOLUTION_NAME: PocketInvest
permissions:
  contents: write
jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.DEVSECRET }}
        tenant-id: ${{env.TENANT_ID}}
        
    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.DEVSECRET }}
        tenant-id: ${{env.TENANT_ID}}
        solution-name: ${{ env.SOLUTION_NAME }}
        solution-output-file: out/exported/${{ env.SOLUTION_NAME }}.zip

    - name: check-solution action
      uses: microsoft/powerplatform-actions/check-solution@v0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.DEVSECRET }}
        tenant-id: ${{env.TENANT_ID}}
        path: out/exported/${{ env.SOLUTION_NAME }}.zip

    - name: unpack-solution action
      if: ${{ success() }}
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: out/exported/${{ env.SOLUTION_NAME }}.zip
        solution-folder: ${{ env.SOLUTION_NAME }}
        solution-type: 'Unmanaged'
        overwrite-files: true
        
    - name: Commit changes
      if: ${{ success() }}
      run: |
        Remove-Item -Path "out/exported/${{ env.SOLUTION_NAME }}.zip" -Recurse -Force
        git config --global user.email "no-reply@github.com"
        git config --global user.name "GitHub Actions"
        git checkout main
        git add --all 
        git commit -m "Updates from the dev environment"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push
