name: Release action
# Call the reusable workflow release-solution-with-inputs.yml
# Release your solution to prod when you create a new release.

on:
  workflow_dispatch:
    
  #release:
  #  types: [created]    
permissions:
  contents: write
jobs:
  Release-solution-PocketInvest:
    uses: ./.github/workflows/02_DEVExport.yml
   
