name: Release action
# Call the reusable workflow release-solution-with-inputs.yml
# Release your solution to prod when you create a new release.

on:
  workflow_dispatch:
    
  release:
    types: [created]    
permissions:
  contents: write
jobs:
  Release-solution-PocketInvest:
    uses: ./.github/workflows/build_artifact_and_import_to_PROD.yml
    with:
      #You can specify the solution name here
      solution_name: PocketInvest
      #Update your values here
      BUILD_ENVIRONMENT_URL: https://pl400-build.crm16.dynamics.com/
      PRODUCTION_ENVIRONMENT_URL: https://pl400-prod.crm16.dynamics.com/
      BUILD_CLIENT_ID: b6fe6c58-23dd-4dcf-b399-6ff32ed654d0
      BUILD_TENANT_ID: 189fc259-0274-4dfb-b187-e2b6dcaf0e88      
      PROD_CLIENT_ID: 886fb551-178c-43f0-9e1d-5720a81a0ec2
      PROD_TENANT_ID: 189fc259-0274-4dfb-b187-e2b6dcaf0e88 
    secrets:
      DEVSECRET: ${{ secrets.DEVSECRET }}
      BUILDSECRET: ${{ secrets.BUILDSECRET }}
      PRODSECRET: ${{ secrets.PRODSECRET }}
