name: testsetversion
# Export solution from DEV environment
#  unpack it and prepare, commit and push

on:
  workflow_dispatch:
    
  release:
    types: [created]    

env:
  ENVIRONMENT_URL: 'https://org859aecd5.crm16.dynamics.com/'
  CLIENT_ID: '20e6d751-0038-4647-ab6e-2ecc5286aec7'
  TENANT_ID: '189fc259-0274-4dfb-b187-e2b6dcaf0e88'
  SOLUTION_NAME: PocketInvest
  SOLUTION_EXPORTED_FOLDER: out/exported/
permissions:
  contents: write
jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
        
    - name: Install PAC
      uses: microsoft/powerplatform-actions/actions-install@v1.1.0
    
    - name: Power Platform Set Online Solution Version
      uses: microsoft/powerplatform-actions/set-online-solution-version@v1.1.0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.DEVSECRET }}
        tenant-id: ${{env.TENANT_ID}}
        name: PocketInvest
        version: ${{github.event.release.tag_name}}
